### ISSUE TITLE
Error since v3.0.4 : Cannot find module './utils' from 'index.js'

### ISSUE THREAD

**Issue by jon301** [jedmao/redux-mock-store#60]
Hi, I've upgraded to the latest version and I encounter this error:

![image](https://user-images.githubusercontent.com/122108/78050532-a3d4e980-737c-11ea-9f6f-05dc7385f703.png)

Is it familiar ?
Thanks for your help

**Comment by zaidchauhan** [comment]
This PR will resolve it - https://github.com/jedmao/redux-mock-store/pull/61
